# Generated by Django 5.1.3 on 2024-12-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_articlecomment_user_alter_video_createdtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='isStaff',
            new_name='is_staff',
        ),
    ]
