# Generated by Django 5.1.3 on 2024-12-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fetchable_url',
            field=models.TextField(null=True),
        ),
    ]
