# Generated by Django 5.1.3 on 2024-12-21 14:02

from django.db import migrations

def modify_fetchable_url(app, schema_editor):
    videos = app.get_model('api', 'Video')
    for video in videos.objects.all():
        video.fetchable_url = f"https://drive.google.com/uc?export=download&id={video.videoUniqueId}"
        video.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_video_fetchable_url'),
    ]

    operations = [
        migrations.RunPython(modify_fetchable_url)
    ]