# Generated by Django 5.1.3 on 2024-12-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20241221_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnailImageFetchableUrl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnailImageUrl',
            field=models.TextField(null=True),
        ),
    ]
