# Generated by Django 5.1.3 on 2024-12-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_video_thumbnailimagefetchableurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnailImageId',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
