# Generated by Django 5.1.3 on 2024-12-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_video_thumbnailimageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnailImageId',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
