# Generated by Django 5.1.3 on 2024-12-29 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_video_thumbnailimageid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TemporarySearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchValue', models.CharField(max_length=255)),
                ('searchDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to='api.temporaryuser')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryArticleComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
                ('parentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.temporaryarticlecomment')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='api.temporaryuser')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryVideoComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('parentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.temporaryvideocomment')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='api.temporaryuser')),
                ('videoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.video')),
            ],
        ),
    ]
