# Generated by Django 5.1.3 on 2024-12-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_articlereaction_temporaryarticlereaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likeNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='likeNum',
            field=models.IntegerField(default=0),
        ),
    ]
