# Generated by Django 5.1.3 on 2024-12-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_article_likenum_video_likenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
