# Generated by Django 5.1.3 on 2025-01-04 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_temporaryuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bookmarkNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='bookmarkNum',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ArticleBookmark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('savedTime', models.DateTimeField(auto_now_add=True)),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryArticleBookmark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('savedTime', models.DateTimeField(auto_now_add=True)),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.temporaryuser')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryVideoBookmark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('savedTime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.temporaryuser')),
                ('videoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoBookmark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('savedTime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.video')),
            ],
        ),
    ]
