# Generated by Django 5.1.3 on 2025-01-05 08:59

import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_article_bookmarknum_video_bookmarknum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryuser',
            name='profileImage',
            field=models.FileField(blank=True, storage=api.storage.S3MediaStorage(), upload_to='Uploads/'),
        ),
    ]
