# Generated by Django 5.1.3 on 2025-01-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_temporaryuser_profileimage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articlebookmark',
            constraint=models.UniqueConstraint(fields=('user', 'articleId'), name='unique_article_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='articlereaction',
            constraint=models.UniqueConstraint(fields=('user', 'articleId'), name='unique_article_reaction'),
        ),
        migrations.AddConstraint(
            model_name='videobookmark',
            constraint=models.UniqueConstraint(fields=('user', 'videoId'), name='unique_video_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='videoreaction',
            constraint=models.UniqueConstraint(fields=('user', 'videoId'), name='unique_video_reaction'),
        ),
    ]
