# Generated by Django 5.1.3 on 2025-01-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_articlebookmark_unique_article_bookmark_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='temporaryarticlebookmark',
            constraint=models.UniqueConstraint(fields=('user', 'articleId'), name='unique_temporary_article_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='temporaryarticlereaction',
            constraint=models.UniqueConstraint(fields=('user', 'articleId'), name='unique_temporary_article_reaction'),
        ),
        migrations.AddConstraint(
            model_name='temporaryvideobookmark',
            constraint=models.UniqueConstraint(fields=('user', 'videoId'), name='unique_temporary_video_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='temporaryvideoreaction',
            constraint=models.UniqueConstraint(fields=('user', 'videoId'), name='unique_temporary_video_reaction'),
        ),
    ]
