# Generated by Django 5.1.3 on 2025-01-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_temporaryarticlebookmark_unique_temporary_article_bookmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryuser',
            name='displayname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
