# Generated by Django 5.1.3 on 2025-02-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_temporaryuser_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleBrandType',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
